/**
 * Descriptions officielles des classes IFRA (51e amendement).
 * Source : IFRA51 CLASSE.xlsx (Coptis).
 * Clés dans l’ordre du certificat : 1, 2, 3, 4, 5A, 5B, 5C, 5D, 6, 7A, 7B, 8, 9, 10A, 10B, 11A, 11B, 12.
 */
export const IFRA_CATEGORY_ORDER = ['1', '2', '3', '4', '5A', '5B', '5C', '5D', '6', '7A', '7B', '8', '9', '10A', '10B', '11A', '11B', '12'] as const

export const IFRA_CATEGORY_DESCRIPTIONS: Record<string, string> = {
  '1': "Produits sans rinçage généralement appliqués sur les lèvres: Produits pour les lèvres de tous types (rouges à lèvres solides et liquides, baumes, transparents ou colorés etc.) Jouets pour enfants",
  '2': "Produits sans rinçage généralement appliqués sur les aisselles: Déodorants et antitranspirants de tous types, y compris tout produit avec une utilisation prévue ou raisonnablement prévisible sur les aisselles ou étiqueté en tant que tel (spray, stick, roll-on, aisselles, déo-cologne, etc.) Sprays pour le corps (y compris les brumes pour le corps)",
  '3': "Produits généralement appliqués sur le visage du bout des doigts: Produits pour les yeux de tous types (ombre à paupières, mascara, eye-liner, maquillage des yeux, masques pour les yeux, patches pour les yeux, etc.), y compris les soins pour les yeux et les hydratants Maquillage du visage et fond de teint Démaquillants pour le visage et les yeux Patches pour les pores du nez Lingettes ou tissus rafraîchissants pour le visage, le cou, les mains, le corps Peinture pour le corps et le visage (pour enfants et adultes) Masques pour le visage et le contour des yeux",
  '4': "Produits parfumés généralement appliqués sur le cou, le visage et les poignets: Parfums fins hydroalcooliques et non hydroalcooliques de tous types (Eau de Toilette, Parfum, Cologne, parfum solide, crème parfumée, après rasage de tous types, etc.) Bracelets parfumés Ingrédients de kits de parfums et de mélanges de parfums pour kits cosmétiques Tampons parfumés, packs de lingettes Bandelettes olfactives pour produits hydroalcooliques",
  '5A': "Produits sans rinçage appliqués sur le visage et le corps à l'aide des mains (paumes): Crèmes pour le corps, Huiles, Lotions de tous types Produits de soins des pieds (crèmes et poudres) Répulsifs d'insectes (destinés à être appliqués sur la peau) Toutes les poudres et talcs (à l'exception des poudres et talcs pour bébés)",
  '5B': "Produits sans rinçage appliqués sur le visage et le corps à l'aide des mains (paumes): Toniques pour le visage Hydratant et crèmes pour le visage (y compris les produits de soins pour la barbe et la moustache)",
  '5C': "Produits sans rinçage appliqués sur le visage et le corps à l'aide des mains (paumes): Crèmes pour les mains Produits de soins des ongles, y compris les crèmes pour les cuticules, etc. Assainissants pour les mains",
  '5D': "Produits sans rinçage appliqués sur le visage et le corps à l'aide des mains (paumes): Crèmes/Laits pour bébés, huiles pour bébés, poudres et talcs pour bébés",
  '6': "Produits avec exposition des lèvres et exposition orale: Dentifrices Bains de bouche, y compris sprays pour l'haleine Poudres dentifrices, languettes, tablettes pour le nettoyage de la bouche",
  '7A': "Produits appliqués sur les cheveux avec contact avec les mains: Traitements capillaires permanents ou autres traitements chimiques pour les cheveux (à rincer) (ex : défrisants), y compris les colorations capillaires à rincer",
  '7B': "Produits appliqués sur les cheveux avec contact avec les mains: Sprays pour les cheveux de tous types (flacons-pompes, sprays aérosols, etc.) Aides au coiffage des cheveux autres qu'en sprays (mousses, gels, conditionneurs sans rinçage) Traitements capillaires permanents ou autres traitements chimiques pour les cheveux (sans rinçage) (ex : défrisants), y compris les colorations capillaires sans rinçage Shampooings secs (shampooings sans eau) Déodorants pour cheveux",
  '8': "Produits avec une exposition anogénitale significative: Lingettes intimes Lingettes pour bébés",
  '9': "Produits à rincer avec exposition du corps et des mains: Pain de savon Shampooings de tous types Nettoyants pour le visage (à rincer) Conditionneurs (à rincer) Savons liquides Nettoyants pour le corps et gels douche de tous types Gels nettoyants, produits pour le bain et shampooings pour bébés Gels pour le bain, mousses, sels, huiles et autres produits ajoutés à l'eau du bain Produits de soins de pieds (quand les pieds sont placés dans un bain) Crèmes à raser de tous types (sticks, gels, mousses, etc.) Tous les produits dépilatoires (y compris pour le visage) et cires pour épilation mécanique Shampooings pour animaux de compagnie",
  '10A': "Produits d'entretien ménager entrant principalement en contact avec les mains: Détergent pour lavage à la main (y compris les concentrés) Prétraitement du linge de tous types (par exemple, pâte, sprays, bâtons) Détergent pour le lavage de la vaisselle à la main (y compris les concentrés) Nettoyants pour surfaces dures de tous types (nettoyants pour salles de bains et cuisines, cire pour meubles, etc.) Détergents pour machines à laver avec contact avec la peau (par exemple, liquides, poudres), y compris les concentrés Kits de nettoyage à sec (impliquant une application manuelle sur le textile) Lingettes pour siège de toilette Assouplissants de tissus de tous types, y compris les lingettes d'assouplissants de tissus Produits d'entretien ménager d'autres types, y compris les nettoyants pour tissus, les nettoyants pour surfaces souples, les nettoyants pour moquettes, les vaporisateurs et les lingettes de polissage pour meubles, les lingettes de nettoyage du cuir, les détachants, les vaporisateurs de régénération des tissus, les produits de traitement pour textiles Cire pour sols Huile parfumée pour lampes, diffuseurs à roseaux, pots-pourris, recharges liquides pour les désodorisants (systèmes sans cartouche), etc. Eau de repassage (eau distillée odorisée) Kits de nettoyage à sec (avec application manuelle sur le textile)",
  '10B': "Produits d'entretien ménager entrant principalement en contact avec les mains: Sprays pour animaux - sprays appliqués sur les animaux de tous types Désodorisants en spray, manuels, y compris aérosol et pompe Insecticides en aérosol/en spray",
  '11A': "Produits destinés à entrer en contact avec la peau, mais avec un transfert minimal du parfum sur la peau à partir d'un substrat inerte: Tampons conventionnels, serviettes, coussinets interlabiaux pour l'hygiène féminine Couches (bébé et adulte) Culotte, serviette pour incontinence adulte Papier hygiénique (sec)",
  '11B': "Produits destinés à entrer en contact avec la peau, mais avec un transfert minimal du parfum sur la peau à partir d'un substrat inerte: Collants avec produits hydratants Chaussettes parfumées, gants Mouchoirs en papier (mouchoirs secs) Serviettes de table Serviettes en papier Sacs emplis de noyaux Masques faciaux (papier/protecteur), par exemple masques chirurgicaux non utilisés comme dispositif médical Engrais solides (granulés ou poudre)",
  '12': "Produits non destinés à un contact direct avec la peau, transfert minime ou insignifiant sur la peau: Bougies de tous types (y compris les bougies encastrées) Détergents pour le lavage en machine avec un contact minimal avec la peau (par exemple, tablettes liquides, dosettes) Désodorisants et parfums automatisés de tous types (aérosols concentrés avec doses mesurées (de 0,05 à 0,5 ml/vaporisation), plug-ins, systèmes fermés, substrat solide, diffusion par membrane, électrique, poudres, sachets parfumés, encens, recharges liquides (cartouches), cristaux désodorisants, diffuseur de voiture solide sans aérosol). Systèmes de diffusion d'air Litière pour chat Etuis de téléphone portable Désodorisants/masques non destinés à entrer en contact avec la peau (par exemple, désodorisants pour machines à sécher les tissus, poudres pour tapis) Kits de nettoyage à sec (placés dans le sèche-linge) Feuilles de séchage et feuilles d'assouplissant Combustibles Insecticides (par exemple, serpentins anti-moustiques, papier, électricité, pour les vêtements) à l'exception des aérosols et des sprays. Bâtons de mousse ou d'encens Détergents et désodorisants pour lave-vaisselle - pour le lavage en machine Jeux de société olfactifs Peintures Articles en plastique (à l'exception des jouets) Gratte et renifle Paquet de senteurs Système de diffusion de parfum (utilisant la technologie de l'air sec) Cirage de chaussures Blocs de jantes (toilettes) Gel de toilette Perles parfumées",
}

/** Retourne la description de la catégorie IFRA (toujours une chaîne non vide pour les 18 classes). */
export function getIfraCategoryDescription(categoryKey: string): string {
  const key = String(categoryKey).trim()
  return IFRA_CATEGORY_DESCRIPTIONS[key] ?? IFRA_CATEGORY_DESCRIPTIONS[key.toUpperCase()] ?? '(Voir IFRA 51e amendement)'
}
