/**
 * Suggestions d'objectifs d'amélioration pour une nouvelle version de formule.
 * Vous pouvez compléter cette liste à partir de vos sujets habituels (copier depuis vos écrans).
 */
export const IMPROVEMENT_GOAL_OPTIONS: string[] = [
  'Aspect / brillance',
  'Aspect / opacité',
  'Aspect / onctuosité',
  'Odeur / parfum',
  'Odeur / neutralité',
  'Texture / fluidité',
  'Texture / épaisseur',
  'Texture / étalement',
  'Stabilité physique',
  'Stabilité chimique',
  'Stabilité à la chaleur',
  'Stabilité au froid',
  'Stabilité cycle gel-dégel',
  'Coût matière première',
  'Coût de revient',
  'Sensorialité / toucher',
  'Sensorialité / après-prise',
  'Résidus / blancheur',
  'Résidus / gras',
  'Conservation / DLC',
  'Conservation / packaging',
  'pH / ajustement',
  'pH / stabilité',
  'Microbiologie',
  'Allergènes / réduction',
  'Allergènes / conformité',
  'Étiquetage INCI',
  'Naturalité / pourcentage bio',
  'Naturalité / conformité COSMOS',
  'Efficacité / actifs',
  'Efficacité / dosage',
  'Tolérance / douceur',
  'Rendement / process',
  'Émulsion / type',
  'Viscosité',
  'Couleur',
  'Autre (saisir ci-dessous)',
]
